### ISSUE TITLE
How do I create an executable?

### ISSUE THREAD

**Issue by fl1pe** [raphaelfrei/yt-video_downloader#1]
I made a script based on yours, but without a graphical interface and I want to send it to a friend, I tried to compile with the "pyinstaller" Followed the step-by-step documentation but could not

**Comment by raphaelfrei** [comment]
Hi! By next week I'll be releasing an video tutorial of how I created my .exe

**Comment by fl1pe** [comment]
Ok, I'm waiting, let me know when I post the video.

**Comment by raphaelfrei** [comment]
Hi! This is the tutorial of how I created an .exe:
https://www.youtube.com/watch?v=6QhJSzSMmj0

**Comment by fl1pe** [comment]
> Hi! This is the tutorial of how I created an .exe: https://www.youtube.com/watch?v=6QhJSzSMmj0

Tu é BR e eu digitando em inglês

**Comment by fl1pe** [comment]
> Hi! This is the tutorial of how I created an .exe: https://www.youtube.com/watch?v=6QhJSzSMmj0

Muito bom, então eu tenho que ta numa maquina windows, eu tentei pelo PYINSTALLER, e eu to usando Linux acho que por isso deu errado, eu criei um msm script, dps se puder da uma olhada agradeço
